# Generated by Django 4.1.6 on 2023-03-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
