# Generated by Django 4.1.6 on 2023-03-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_members_joined_date_alter_members_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='members',
            new_name='Member',
        ),
    ]
